//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFCalendarKotowski.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\NTR17Z.mdf;In" +
            "tegrated Security=True")]
        public string NTR17ZConnectionString {
            get {
                return ((string)(this["NTR17ZConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;Initial Catalog=C:\\USERS\\ADRIAN\\SOURCE\\REPOS\\W" +
            "PFCALENDARKOTOWSKIDB\\WPFCALENDARKOTOWSKI\\MODEL\\CALENDAR.MODEL.STORAGECONTEXT.MDF" +
            ";Integrated Security=True")]
        public string C__USERS_ADRIAN_SOURCE_REPOS_WPFCALENDARKOTOWSKIDB_WPFCALENDARKOTOWSKI_MODEL_CALENDAR_MODEL_STORAGECONTEXT_MDFConnectionString {
            get {
                return ((string)(this["C__USERS_ADRIAN_SOURCE_REPOS_WPFCALENDARKOTOWSKIDB_WPFCALENDARKOTOWSKI_MODEL_CALE" +
                    "NDAR_MODEL_STORAGECONTEXT_MDFConnectionString"]));
            }
        }
    }
}
